name: Flutter_Android

on:
  push:
    tags:
      - v*

permissions: write-all

jobs:
  process:
    name: all process
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17' # 或者使用 '1.8', '9', '10', '12', '13', '14', '15', '16', '17' 等版本号
          distribution: 'adopt' # 可选，如 'adopt', 'zulu', 'liberica', 'oracle', 'corretto' 等

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.1"

      - name: get dependencies
        run: flutter pub get

      - name: build flutter
        run: flutter build apk --release -t lib/main_prd.dart

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
